### ISSUE TITLE
Incorperate Frontend templates from Observatory-new

### ISSUE THREAD

**Issue by Alfriadox** [rcos/Telescope#50]
See work on @rcos/observatory-new

**Comment by rushsteve1** [comment]
So I think this is part of a larger discussion on the future of the two versions of Observatory and what we should do going forward. Currently both are in different states of semi-completion, I think Observatory-new is slightly farther along though and has a mostly finalized UI/UX and some nice features.

With the new central database and API whatever we do needs to be built on that. Whether it interfaces with Postgres directly or through the API is something that would need to be figured out. If we use Postgres directly then all models and queries would also have to be adjusted, though this is likely the case no matter what.

There's also the question of authentication, and whether we want to be responsible for that or delegate it to GitHub or similar using OAuth. While tying ourselves to GitHub isn't ideal, we effectively already are tied to it (this repo for example).

All that said, I think we need to decide what we're going to do and work together on it. I don't want to fracture development any more than it currently is.

**Comment by Alfriadox** [comment]
I agree. I think there is a difference between tying telescope development to GitHub and tying all of RCOS's membership to GitHub. We should avoid the second one if we can.

**Comment by rushsteve1** [comment]
So to migrate the Observatory-new templates then Telescope would need to switch to [Askama](https://github.com/djc/askama) with Askama-actix.

Back on the subject of authentication, one major problem is that under the current [central RCOS database schema
](/rcos/rcos-data) the database doesn't store or bother with credentials at all. Meaning that would have to be changed to accommodate. Using Oauth would sidestep this problem, and all the general security issues with having our own authentication.

The biggest problem though is that I think both of these are blocked by #61 
The template change is only like, soft-blocked though.

**Comment by Alfriadox** [comment]
Now that we figured out the Auth and database stuff on #61, I think we can look at templates again. I'm not sure if it would make more sense to add the Askama templates as-is (and add Askama as a dependency) or translate them to Handlebars to match the existing templates. What's your opinion?

**Comment by Alfriadox** [comment]
As https://github.com/rcos/observatory-new has been archived at this point, I am closing this issue. The two projects are different enough that migrating old templates would likely be more effort than writing new ones.
